(*
 * THIS IS AN AUTO-GENERATED FILE PRODUCED BY URUZ!
 * DO NOT EDIT THIS FILE, since any changes will be
 * lost when the build is reset via "make clean".
 * This file is based on a user-specified EBNF
 * grammar, which can be edited as desired.
 *)

open Lexing;;
open Parsing;;
(* open Flags;; *)
let eq_base (a : 'a) (b : 'a) : bool = (a = b) ;;
let rec eq_option (f : 'a -> 'a -> bool) (a : 'a option) (b : 'a option) : bool =
   match (a,b) with
   | (None,None) -> true
   | (Some(a),Some(b)) -> (f a b)
   | _ -> false
;;
let eq_pair (f1 : 'a -> 'a -> bool) (f2 : 'b -> 'b -> bool) ((p1a,p1b) : 'a * 'b) ((p2a,p2b) : 'a * 'b) : bool = ((f1 p1a p2a) && (f2 p1b p2b)) ;;
let eq_list (f : 'a -> 'a -> bool) (l1 : 'a list) (l2 : 'a list) : bool = try List.fold_left2 (fun res l1i l2i -> res && (f l1i l2i)) true l1 l2 with _ -> false;;

let rec str_option (f : 'a -> string) (o : 'a option) : string =
   match o with
   | None -> ""
   | Some(a) -> (f a)
;;

let rec str_pair (f : 'a -> string) (g : 'b -> string) ((a,b) : ('a * 'b)) : string =
   (f a)^""^
   (g b)
;;

let rec str_list (f : 'a -> string) (l : 'a list) : string =
   str_list_helper f l true

and str_list_helper (f : 'a -> string) (l : 'a list) (first : bool) : string =
   match l with
   | [] -> ""
   | a::more -> ((if (not first) then "" else "")^(f a)^(str_list_helper f more false))
let rec str_x_list (f : 'a -> string) (il : 'a list) (comma : string) : string = 
    (fst (List.fold_left
    (fun (str,flag) i ->
      (str^(if flag then "" else comma)^(f i), false)
    ) ("",true) il))
;;

  module StringSet = Set.Make(
  struct
    type t = string
    let compare = compare
  end)

  module IntMap = Map.Make(
  struct
    type t = int
    let compare = compare
  end)

  module StringMap = Map.Make(
  struct
    type t = string
    let compare = compare
  end)

  let my_unescaped s =
    let s = Str.global_replace (Str.regexp "[\\][\r][\n]") "" s in
    let s2 = Str.global_replace (Str.regexp "[\\][\n]") "" s in
    Scanf.unescaped s2

  let strip_quotes (s : string) : (string*bool) =
    let len = String.length s in
    if ((len >= 2) && (String.get s 0)='"' && (String.get s (len-1))='"')
    then (String.sub s 1 (len-2),true) else (s,false)

(* AST Data Structure *)

type start_t = 
   | JavascriptProgram of pos_t * program_t
   | SexpProgram of pos_t * sexp_t
   | TestProgram of pos_t * (unit_test_t list)

 and sexp_t = 
   | IdentAtom of pos_t * ident_t
   | StrAtom of pos_t * string
   | NumAtom of pos_t * float
   | BoolAtom of pos_t * bool
   | List of pos_t * sexp_t list

 and sexp1_t = sexp_t

 and sexp1_2_1_t = (sexp_t list)

 and tests_t = (unit_test_t list)

 and tests_0_0_t = ((unit_test_t list) list)

 and unit_test_t = (ident_t * StringSet.t * ident_t * string option * string option * sexp_t * sexp_t)

 and idents_t = (ident_t list)

 and test_t = (unit_test_t list)

 and test_0_1_t = ((ident_t list) option)

 and sexp2_t = sexp_t

 and program_t = 
   | ExprProgram of pos_t * expr_t
   | StmtProgram of pos_t * stmt_t * program_t

 and stmt_t = 
   | ConstStmt of pos_t * ident_t * expr_t
   | LetStmt of pos_t * ident_t * expr_t
   | AssignStmt of pos_t * expr_t * expr_t

 and typ_t = 
   | UnitType
   | BoolType
   | NumType
   | StrType
   | TupleType of typ_t list
   | FuncType of typ_t * typ_t

 and var_access_t = 
   | Mutable
   | Immutable

 and uop_t = 
   | NotUop
   | NegUop

 and bop_t = 
   | AndBop
   | OrBop
   | PlusBop
   | MinusBop
   | TimesBop
   | DivBop
   | EqBop
   | NeqBop
   | LtBop
   | LteBop
   | GtBop
   | GteBop

 and expr_t = 
   | VarExpr of pos_t * ident_t
   | ValExpr of pos_t * value_t
   | BlockExpr of pos_t * block_t
   | FuncExpr of pos_t * lambda_t
   | UopExpr of pos_t * uop_t * expr_t
   | BopExpr of pos_t * expr_t * bop_t * expr_t
   | IfExpr of pos_t * expr_t * expr_t * expr_t
   | PrintExpr of pos_t * expr_t
   | CallExpr of pos_t * expr_t * expr_t list
   | FieldExpr of pos_t * expr_t * ident_t
   | ObjectExpr of pos_t * field_t list

 and expr1_t = expr_t

 and value_t = 
   | NumVal of float
   | BoolVal of bool
   | StrVal of string
   | UndefVal
   | ClosureVal of name_map_t * lambda_t
   | RefVal of address_t

 and ident_t = string

 and address_t = int

 and typed_ident_t = (ident_t * typ_t option)

 and name_map_t = (int StringMap.t)

 and environment_t = (name_map_t list * ident_map_t)

 and ident_map_t = ((var_access_t * value_t) IntMap.t)

 and lambda_t = (ident_t option * typed_ident_t list * block_t * typ_t option)

 and heap_t = (object_t list)

 and object_t = (value_t StringMap.t)

 and value1_t = value_t

 and lambda1_t = lambda_t

 and lambda1_0_1_t = (string option)

 and block_t = 
   | ReturnBlock of pos_t * expr_t
   | StmtBlock of pos_t * stmt_t * block_t

 and field_list_t = (field_t list)

 and field_list_1_1_t = (field_list_1_1_0_t list)

 and field_list_1_1_0_t = 
   | FieldList_1_1_0_0 of pos_t * (ident_t * expr_t)

 and expr_list_t = (expr_t list)

 and expr_list_1_1_t = (expr_list_1_1_0_t list)

 and expr_list_1_1_0_t = 
   | ExprList_1_1_0_0 of pos_t * expr_t

 and ident_list_t = (ident_t list)

 and ident_list_1_1_t = (ident_list_1_1_0_t list)

 and ident_list_1_1_0_t = 
   | IdentList_1_1_0_0 of pos_t * string

 and field_t = (ident_t * expr_t)

 and bool_t = bool

(* data type for file positions *)
and pos_t = NoPos | Pos of string*int*int (* file,line,col *)

let filename = ref ""

exception Parse_error of string;;
exception Lexing_error of string;;
exception General_error of string;;

(* do_error p s
 *
 * Print error message
 *
 * p - the location of the error
 * s - the error message
 *
 * returns unit
 *)
let do_error (p : pos_t) (s : string) : string =
   ("Error"^
   (match p with
   | NoPos -> ""
   | Pos(file_name,line_num,col_num) -> (" in '"^file_name^
    "' on line "^(string_of_int line_num)^" col "^(string_of_int
    col_num))
   )^
   (": "^s^"\n"))
;;

let die_error (p : pos_t) (s : string) =
   raise (General_error(do_error p s))
;;

(* gets a pos data structure using the current lexing pos *)
let get_current_pos () =
   let p         = symbol_start_pos () in
   let file_name = !filename (*p.Lexing.pos_fname*)  in
   let line_num  = p.Lexing.pos_lnum   in
   let col_num   = (p.Lexing.pos_cnum-p.Lexing.pos_bol+1) in
   Pos(file_name,line_num,col_num)
;;

(* gets a pos data structure from a lexing position *)
let get_pos (p : Lexing.position) =
   let file_name = !filename (*p.Lexing.pos_fname*) in
   let line_num  = p.Lexing.pos_lnum  in
   let col_num   = (p.Lexing.pos_cnum-p.Lexing.pos_bol+1) in
   Pos(file_name,line_num,col_num)
;;

(* dies with a general position-based error *)
let pos_error (s : string) (p : position) = 
   do_error (get_pos p) s
;;

(* dies with a parse error s *)
let parse_error (s : string) = 
   raise (Parse_error(pos_error s (symbol_end_pos ())))
;;

(* dies with a lexing error *)
let lex_error (s : string) (lexbuf : Lexing.lexbuf) = 
   raise (Lexing_error(pos_error s (Lexing.lexeme_end_p lexbuf)))
;;

(* updates the lexer position to the next line
 * (this is used since we skip newlines in the
 *  lexer, but we still wish to remember them
 *  for proper line positions) *)
let do_newline lb = 
   Lexing.new_line lb
;;

(* dies with a system error s *)
let die_system_error (s : string) =
   output_string stderr s;
   output_string stderr "\n";
   exit 1
;;

let rec count_newlines s lb = match s with
  | "" -> 0
  | _  -> let c = String.sub s 0 1 in
          let cs = String.sub s 1 ((String.length s)-1) in
          if (c="\n") then (do_newline lb; 1+(count_newlines cs lb))
                      else (count_newlines cs lb)
;;



(* obtain most recent binding of variable x in environment env *)
let read_environment : (environment_t*string) -> (var_access_t*value_t) option = fun (env,x) ->
  let (name_map,val_map) = env in
  try Some(IntMap.find (StringMap.find x (List.hd name_map)) val_map)
  with (Failure(_) | Not_found) -> None

(* overwrite the old value of variable x in environment env *)
let update_environment : (environment_t*string*(var_access_t*value_t)) -> (environment_t*(var_access_t*value_t) option) = fun (env,x,v) ->
  let (name_map,val_map) = env in
  try
    let id = (StringMap.find x (List.hd name_map)) in
    let (access,v_old) = IntMap.find id val_map in
    let new_item = (match access with
    | Mutable -> v
    | Immutable -> (access,v_old)) in
    ((name_map,IntMap.add id new_item val_map), Some(new_item))
  with (Failure(_) | Not_found) -> (env,None)

let unique_id = ref 0

(* push a new binding for variable x into the environment env *)
let push_environment : (environment_t*string*(var_access_t*value_t)) -> environment_t = fun (env,x,v) ->
  let id = !unique_id in
  unique_id := !unique_id + 1;
  let (name_map,val_map) = env in
  let nm2 = (match name_map with
    | a::more -> (StringMap.add x id a)::more
    | _ -> [StringMap.add x id StringMap.empty]
  ) in
  (nm2, IntMap.add id v val_map)

let pop_environment : environment_t -> environment_t = fun env -> match env with
  | ((a::more),d) -> (more,d)
  | _ -> env

(* empty environment - used for testing *)
let empty_env = ([StringMap.empty],IntMap.empty)

(* floating-point equality - used only for testing functionality *)
let eq_float = fun (n1,n2) -> (Float.compare n1 n2)=0

(* convert JavaScript numeric value to float *)
let js_float_of_string = fun s ->
  try float_of_string s
  with Failure(_) -> (
    try Int64.to_float (Int64.of_string s)
    with Failure(_) -> raise (Failure(Printf.sprintf "js_float_of_string: %s" s))
  )

(* convert float to string *)
let str_float = fun n ->
  if (eq_float (n,Float.nan)) then "NaN"
  else if (eq_float (n,Float.infinity)) then "Infinity"
  else if (eq_float (n,Float.neg_infinity)) then "-Infinity"
  else
    let s = Printf.sprintf "%g" n in
    let len1 = (String.length s)-1 in
    if (String.get s len1)='.'
    then String.sub s 0 len1
    else s

let rec str_typ (t : typ_t) = match t with
| UnitType -> "undefined"
| BoolType -> "boolean"
| NumType -> "number"
| StrType -> "string"
| TupleType(tl) -> Printf.sprintf "(%s)" (str_x_list str_typ tl ", ")
| FuncType(t1,t2) -> Printf.sprintf "%s -> %s" (str_typ t1) (str_typ t2)

let str_access = fun a -> match a with
| Mutable   -> "mut"
| Immutable -> "const"

let rec str_program (p : program_t) = match p with
  | ExprProgram(_,e) -> str_expr e
  | StmtProgram(_,s,p) -> Printf.sprintf "%s; %s" (str_stmt s) (str_program p)

and str_stmt (s : stmt_t) = match s with
  | ConstStmt(_,v,e) -> Printf.sprintf "const %s = %s" (str_ident v) (str_expr e)
  | LetStmt(_,v,e) -> Printf.sprintf "let %s = %s" (str_ident v) (str_expr e)
  | AssignStmt(_,e1,e2) -> Printf.sprintf "%s = %s" (str_expr e1) (str_expr e2)

and str_expr (e : expr_t) = match e with
  | VarExpr(_,v) -> Printf.sprintf "%s" (str_ident v)
  | ValExpr(_,v) -> Printf.sprintf "%s" (str_value v)
  | BlockExpr(_,b) -> Printf.sprintf "%s" (str_block b)
  | FuncExpr(_,f) -> Printf.sprintf "%s" (str_lambda f)
  | UopExpr(_,uop,e) -> Printf.sprintf "(%s %s)" (str_uop uop) (str_expr e)
  | BopExpr(_,e1,bop,e2) -> Printf.sprintf "(%s %s %s)" (str_expr e1) (str_bop bop) (str_expr e2)
  | CallExpr(_,(VarExpr(_) as e1),e2) -> Printf.sprintf "%s(%s)" (str_expr e1) (str_x_list str_expr e2 ", ")
  | CallExpr(_,e1,e2) -> Printf.sprintf "(%s)(%s)" (str_expr e1) (str_x_list str_expr e2 ", ")
  | IfExpr(_,e1,e2,e3) -> Printf.sprintf "(%s ? %s : %s)" (str_expr e1) (str_expr e2) (str_expr e3)
  | PrintExpr(_,e) -> Printf.sprintf "console.log(%s)" (str_expr e)
  | FieldExpr(_,e,f) -> Printf.sprintf "%s.%s" (str_expr e) (str_ident f)
  | ObjectExpr(_,fl) -> Printf.sprintf "{ %s }" (str_x_list (fun (f,e) -> Printf.sprintf "%s:%s" (str_ident f) (str_expr e)) fl ", ")

and str_bop (b : bop_t) = match b with
  | AndBop -> "&&"
  | OrBop -> "||"
  | PlusBop -> "+"
  | MinusBop -> "-"
  | TimesBop -> "*"
  | DivBop -> "/"
  | EqBop -> "==="
  | NeqBop -> "!=="
  | LtBop -> "<"
  | LteBop -> "<="
  | GtBop -> ">"
  | GteBop -> ">="

and str_uop (u : uop_t) = match u with
  | NotUop -> "!"
  | NegUop -> "-"

and str_value (v : value_t) = str_value_helper v false

and str_value_helper (v : value_t) (print_special : bool) = match v with
  | NumVal(n) -> str_float n
  | BoolVal(b) -> string_of_bool b
  | StrVal(s) -> Printf.sprintf "\"%s\"" s
  | UndefVal -> "undefined"
  | ClosureVal(nm,f) ->
    if print_special then Printf.sprintf "CL<%s; %s>" (str_name_map nm) (str_lambda f)
    else str_lambda f
  | RefVal(addr) -> Printf.sprintf "REF<%d>" addr

and str_lambda (name,params,bl,_) =
  Printf.sprintf "function %s(%s) { %s }" (str_option (fun x -> x) name) (str_x_list str_typed_var params ", ") (str_block bl)

and str_block (bl : block_t) = match bl with
  | ReturnBlock(_,e) -> Printf.sprintf "return %s" (str_expr e)
  | StmtBlock(_,s,bl) -> Printf.sprintf "%s; %s" (str_stmt s) (str_block bl)

and str_typed_var (tv : typed_ident_t) = match tv with
  | (v,t) -> v

and str_ident (x : ident_t) = x

and str_name_map = fun nm ->
  "{"^(str_x_list (fun (k,i) -> Printf.sprintf "%s->%d" k i) (StringMap.bindings nm) ", ")^"}"

and str_ident_map = fun im ->
  "{"^(str_x_list (fun (k,(m,v)) -> Printf.sprintf "%d->(%s,%s)" k (str_access m) (str_value_helper v true)) (IntMap.bindings im) ", ")^"}"

(* formatting of S-Expressions *)
let rec str_sexp = fun e -> match e with
| IdentAtom(_,s) -> Printf.sprintf "%s" s
| NumAtom(_,n) -> str_float n
| BoolAtom(_,b) -> string_of_bool b
| StrAtom(_,s) -> Printf.sprintf "\"%s\"" s
| List(_,sl) -> Printf.sprintf "(%s)" (str_x_list str_sexp sl " ")

let rec eq_typ (t1 : typ_t) (t2 : typ_t) = match (t1,t2) with
| (UnitType,UnitType) -> true
| (BoolType,BoolType) -> true
| (NumType,NumType) -> true
| (StrType,StrType) -> true
| (TupleType(tl1),TupleType(tl2)) -> eq_list eq_typ tl1 tl2
| (FuncType(ta1,tb1),FuncType(ta2,tb2)) -> (eq_typ ta1 ta2) && (eq_typ tb1 tb2)
| _ -> false

let rec eq_program (p1 : program_t) (p2 : program_t) = match (p1,p2) with
  | (ExprProgram(_,e1),ExprProgram(_,e2)) -> eq_expr e1 e2
  | (StmtProgram(_,s1,p1),StmtProgram(_,s2,p2)) -> (eq_stmt s1 s2) && (eq_program p1 p2)
  | _ -> false

and eq_stmt (s1 : stmt_t) (s2 : stmt_t) = match (s1,s2) with
  | (ConstStmt(_,v1,e1),ConstStmt(_,v2,e2)) -> (eq_ident v1 v2) && (eq_expr e1 e2)
  | (LetStmt(_,v1,e1),LetStmt(_,v2,e2)) -> (eq_ident v1 v2) && (eq_expr e1 e2)
  | (AssignStmt(_,ea1,eb1),AssignStmt(_,ea2,eb2)) -> (eq_expr ea1 ea2) && (eq_expr eb1 eb2)
  | _ -> false

and eq_expr (e1 : expr_t) (e2 : expr_t) = match (e1,e2) with
  | (VarExpr(_,v1),VarExpr(_,v2)) -> eq_ident v1 v2
  | (ValExpr(_,v1),ValExpr(_,v2)) -> eq_value v1 v2
  | (BlockExpr(_,b1),BlockExpr(_,b2)) -> eq_block b1 b2
  | (FuncExpr(_,f1),FuncExpr(_,f2)) -> eq_lambda f1 f2
  | (UopExpr(_,uop1,e1),UopExpr(_,uop2,e2)) -> (eq_uop uop1 uop2) && (eq_expr e1 e2)
  | (BopExpr(_,ea1,bop1,eb1),BopExpr(_,ea2,bop2,eb2)) -> (eq_expr ea1 ea2) && (eq_bop bop1 bop2) && (eq_expr eb2 eb2)
  | (CallExpr(_,ea1,eb1),CallExpr(_,ea2,eb2)) -> (eq_expr ea1 ea2) && (eq_list eq_expr eb1 eb2)
  | (IfExpr(_,ea1,eb1,ec1),IfExpr(_,ea2,eb2,ec2)) -> (eq_expr ea1 ea2) && (eq_expr eb1 eb2) && (eq_expr ec1 ec2)
  | (PrintExpr(_,e1),PrintExpr(_,e2)) -> eq_expr e1 e2
  | (FieldExpr(_,e1,f1),FieldExpr(_,e2,f2)) -> (eq_expr e1 e2) && (eq_ident f1 f2)
  | (ObjectExpr(_,fl1),ObjectExpr(_,fl2)) -> eq_list (fun (i1,e1) (i2,e2) -> (eq_ident i1 i2) && (eq_expr e1 e2)) fl1 fl2
  | _ -> false

and eq_bop (b1 : bop_t) (b2 : bop_t) = match (b1,b2) with
  | (AndBop,AndBop) -> true
  | (OrBop,OrBop) -> true
  | (PlusBop,PlusBop) -> true
  | (MinusBop,MinusBop) -> true
  | (TimesBop,TimesBop) -> true
  | (DivBop,DivBop) -> true
  | (EqBop,EqBop) -> true
  | (NeqBop,NeqBop) -> true
  | (LtBop,LtBop) -> true
  | (LteBop,LteBop) -> true
  | (GtBop,GtBop) -> true
  | (GteBop,GteBop) -> true
  | _ -> false

and eq_uop (u : uop_t) (u : uop_t) = match (u,u) with
  | (NotUop,NotUop) -> true
  | (NegUop,NegUop) -> true
  | _ -> false

and eq_value (v1 : value_t) (v2 : value_t) = match (v1,v2) with
  | (NumVal(n1),NumVal(n2)) -> eq_float (n1,n2)
  | (BoolVal(b1),BoolVal(b2)) -> b1=b2
  | (StrVal(s1),StrVal(s2)) -> s1=s2
  | (UndefVal,UndefVal) -> true
  | (ClosureVal(nm1,l1),ClosureVal(nm2,l2)) ->
    StringMap.equal (=) nm1 nm2 && eq_lambda l1 l2
  | (RefVal(a1),RefVal(a2)) -> a1=a2
  | _ -> false

and eq_lambda (name1,params1,bl1,t1) (name2,params2,bl2,t2) =
  (eq_option eq_ident name1 name2) && (eq_list eq_typed_var params1 params2)
  && (eq_block bl1 bl2) && (eq_option eq_typ t1 t2)

and eq_block (bl1 : block_t) (bl2 : block_t) = match (bl1,bl2) with
  | (ReturnBlock(_,e1),ReturnBlock(_,e2)) -> eq_expr e1 e2
  | (StmtBlock(_,s1,bl1),StmtBlock(_,s2,bl2)) -> (eq_stmt s1 s2) && (eq_block bl1 bl2)
  | _ -> false

and eq_typed_var (tv1 : typed_ident_t) (tv2 : typed_ident_t) = match (tv1,tv2) with
  | ((v1,t1),(v2,t2)) -> (eq_ident v1 v2) && (eq_option eq_typ t1 t2)

and eq_ident (x1 : ident_t) (x2 : ident_t) =
  (x1=x2)

(* equality of S-Expressions *)
let rec eq_sexp (s1 : sexp_t) (s2 : sexp_t) = match (s1,s2) with
  | (IdentAtom(_,s1),IdentAtom(_,s2)) -> s1=s2
  | (NumAtom(_,n1),NumAtom(_,n2)) -> eq_float (n1,n2)
  | (BoolAtom(_,b1),BoolAtom(_,b2)) -> b1=b2
  | (StrAtom(_,s1),StrAtom(_,s2)) -> s1=s2
  | (List(_,sl1),List(_,sl2)) -> eq_list eq_sexp sl1 sl2
  | _ -> false

(* convert value to float *)
let to_num = fun (v : value_t) -> match v with
| NumVal(n) -> n
| BoolVal(true) -> 1.0
| BoolVal(false) -> 0.0
| StrVal(s) -> 
  if (String.trim s)="" then 0.0
  else (try js_float_of_string s with Failure(_) -> Float.nan)
| UndefVal -> Float.nan
| ClosureVal(_,_) -> Float.nan
| RefVal(_) -> Float.nan

(* convert value to bool *)
let to_bool = fun (v : value_t) -> match v with
| NumVal(n) -> if (eq_float (n,0.0) || eq_float (n,Float.nan)) then false else true
| BoolVal(b) -> b
| StrVal("") -> false
| StrVal(_) -> true
| UndefVal -> false
| ClosureVal(_,_) -> true
| RefVal(_) -> true

(* convert value to string *)
let to_str = fun (v : value_t) -> match v with
| NumVal(n) -> str_float n
| BoolVal(b) -> string_of_bool b
| StrVal(s) -> s
| UndefVal -> "undefined"
| ClosureVal(_,_) -> str_value v
| RefVal(_) -> "[object Object]"

let rec str_environment = fun e -> match e with
| (nml,im) ->
  Printf.sprintf "([%s],\n%s)"
  (str_x_list str_name_map nml "; ")
  (str_ident_map im)

and str_environment_simple: environment_t -> string = fun e -> "{"^(match e with
| ((nm::_),im) ->
  let nm2 = StringMap.map (fun v -> try str_value_helper (snd (IntMap.find v im)) true with _ -> "?") nm in
  Printf.sprintf "%s"
  (str_x_list (fun (k,v) -> Printf.sprintf "%s->%s" k v) (StringMap.bindings nm2) ", ")
| _ -> "")^"}"

and str_heap = fun h ->
  "["^(str_x_list str_object h ", ")^"]"

and str_object = fun o ->
  "{"^(str_x_list (fun (k,v) -> Printf.sprintf "%s->%s" k (str_value v)) (StringMap.bindings o) ", ")^"}"

(* exception indicating that a program is more
 * than just a single expression *)
exception NotExpr of program_t
(* exception indicating unimplemented input
 * expression *)
exception ImmutableVar of ident_t
exception UndeclaredVar of ident_t
exception InvalidCall of expr_t
exception UnimplementedExpr of expr_t 
exception UnimplementedStmt of stmt_t 
exception RefError of expr_t 

let eq_exn = fun ex1 ex2 -> match (ex1,ex2) with
| (NotExpr(p1),NotExpr(p2)) -> eq_program p1 p2
| (ImmutableVar(i1),ImmutableVar(i2)) -> i1=i2
| (UndeclaredVar(i1),UndeclaredVar(i2)) -> i1=i2
| (InvalidCall(e1),InvalidCall(e2)) -> eq_expr e1 e2
| (UnimplementedExpr(e1),UnimplementedExpr(e2)) -> eq_expr e1 e2
| (UnimplementedStmt(s1),UnimplementedStmt(s2)) -> eq_stmt s1 s2
| (RefError(e1),RefError(e2)) -> eq_expr e1 e2
| (ex1,ex2) -> ex1=ex2

(* add printer for above exceptions *)
let _ = Printexc.register_printer (fun ex -> match ex with
| NotExpr(p) -> Some(Printf.sprintf "NotExpr(%s)" (str_program p))
| ImmutableVar(i) -> Some(Printf.sprintf "ImmutableVar(%s)" i)
| UndeclaredVar(i) -> Some(Printf.sprintf "UndeclaredVar(%s)" i)
| InvalidCall(e) -> Some(Printf.sprintf "InvalidCall(%s)" (str_expr e))
| UnimplementedExpr(e) -> Some(Printf.sprintf "Unimplemented(%s)" (str_expr e))
| UnimplementedStmt(s) -> Some(Printf.sprintf "Unimplemented(%s)" (str_stmt s))
| RefError(e) -> Some(Printf.sprintf "RefError(%s)" (str_expr e))
| _ -> None)

let rec sexp_to_program (e : sexp_t) : program_t =
(*Printf.printf "sexp_to_program: %s\n" (str_sexp e);*)
match e with
| List(p,[IdentAtom(_,"expr_program");e]) -> ExprProgram(p,sexp_to_expr e)
| List(p,[IdentAtom(_,"stmt_program");s;pr]) -> StmtProgram(p,sexp_to_stmt s,sexp_to_program pr)
| _ -> failwith "sexp_to_program" (* TODO XXX *)

and sexp_to_stmt (e : sexp_t) : stmt_t = match e with
| List(p,[IdentAtom(_,"const_stmt");IdentAtom(_,i);e]) -> ConstStmt(p,i,sexp_to_expr e)
| List(p,[IdentAtom(_,"let_stmt");IdentAtom(_,i);e]) -> LetStmt(p,i,sexp_to_expr e)
| List(p,[IdentAtom(_,"assign_stmt");e1;e2]) -> AssignStmt(p,sexp_to_expr e1,sexp_to_expr e2)
| _ -> failwith "sexp_to_stmt" (* TODO XXX *)

and sexp_to_expr (e : sexp_t) : expr_t = match e with
| List(p,[IdentAtom(_,"val_expr");v]) -> ValExpr(p,sexp_to_value v)
| List(p,[IdentAtom(_,"var_expr");IdentAtom(_,i)]) -> VarExpr(p,i)
| List(p,[IdentAtom(_,"block_expr");b]) -> BlockExpr(p,sexp_to_block b)
| List(p,[IdentAtom(_,"func_expr");f]) -> FuncExpr(p,sexp_to_lambda f)
| List(p,[IdentAtom(_,"uop_expr");uop;e]) -> UopExpr(p,sexp_to_uop uop,sexp_to_expr e)
| List(p,[IdentAtom(_,"bop_expr");e1;bop;e2]) -> BopExpr(p,sexp_to_expr e1,sexp_to_bop bop,sexp_to_expr e2)
| List(p,IdentAtom(_,"call_expr")::e1::el) -> CallExpr(p,sexp_to_expr e1,List.map sexp_to_expr el)
| List(p,[IdentAtom(_,"if_expr");e1;e2;e3]) -> IfExpr(p,sexp_to_expr e1,sexp_to_expr e2,sexp_to_expr e3)
| List(p,[IdentAtom(_,"print_expr");e]) -> PrintExpr(p,sexp_to_expr e)
| List(p,[IdentAtom(_,"field_expr");e;IdentAtom(_,f)]) -> FieldExpr(p,sexp_to_expr e,f)
| List(p,IdentAtom(_,"object_expr")::fl) -> ObjectExpr(p,List.map sexp_to_field fl)
| _ -> failwith (Printf.sprintf "sexp_to_expr: %s" (str_sexp e))

and sexp_to_field (e : sexp_t) : field_t = match e with
| List(p,[IdentAtom(_,i);e]) -> (i, sexp_to_expr e)
| _ -> failwith (Printf.sprintf "sexp_to_expr: %s" (str_sexp e))

and sexp_to_block (e : sexp_t) : block_t = match e with
| List(p,[IdentAtom(_,"return_block");e]) -> ReturnBlock(p,sexp_to_expr e)
| List(p,[IdentAtom(_,"stmt_block");s;b]) -> StmtBlock(p,sexp_to_stmt s,sexp_to_block b)
| _ -> failwith "sexp_to_block" (* TODO XXX *)

and sexp_to_uop (e : sexp_t) : uop_t = match e with
| IdentAtom(_,"neg") -> NegUop
| IdentAtom(_,"not") -> NotUop
| _ -> failwith "sexp_to_uop" (* TODO XXX *)

and sexp_to_bop (e : sexp_t) : bop_t = match e with
| IdentAtom(_,"and") -> AndBop
| IdentAtom(_,"or") -> OrBop
| IdentAtom(_,"plus") -> PlusBop
| IdentAtom(_,"minus") -> MinusBop
| IdentAtom(_,"times") -> TimesBop
| IdentAtom(_,"div") -> DivBop
| IdentAtom(_,"eq") -> EqBop
| IdentAtom(_,"neq") -> NeqBop
| IdentAtom(_,"lt") -> LtBop
| IdentAtom(_,"lte") -> LteBop
| IdentAtom(_,"gt") -> GtBop
| IdentAtom(_,"gte") -> GteBop
| _ -> failwith "sexp_to_bop" (* TODO XXX *)

and sexp_to_value (e : sexp_t) : value_t = match e with
| IdentAtom(_,"undef_val") -> UndefVal
| List(_,[IdentAtom(_,"num_val");NumAtom(p, n)]) -> NumVal(n)
| List(_,[IdentAtom(_,"bool_val");BoolAtom(p, b)]) -> BoolVal(b)
| List(_,[IdentAtom(_,"str_val");StrAtom(p, s)]) -> StrVal(s)
| List(_,[IdentAtom(_,"ref_val");NumAtom(_,addr)]) -> RefVal(int_of_float addr)
| List(_,[IdentAtom(_,"closure_val");l]) -> ClosureVal(StringMap.empty,sexp_to_lambda l)
| _ -> failwith "sexp_to_value" (* TODO XXX *)

and sexp_to_lambda (e : sexp_t) : lambda_t = match e with
| List(ps,name::List(_,params)::[b]) -> (
  (match name with List(_,[n]) -> Some(sexp_to_ident n) | _ -> None),
  List.map (fun s -> (sexp_to_ident s, None)) params,
  sexp_to_block b,
  None
)
| _ -> failwith "sexp_to_lambda" (* TODO XXX *)

and sexp_to_ident (e : sexp_t) : ident_t = match e with
| IdentAtom(_,i) -> i
| _ -> failwith "sexp_to_ident" (* TODO XXX *)

let make_sexp p name l = List(p,[IdentAtom(p,name)]@l)

let rec program_to_sexp (p : program_t) : sexp_t = match p with
| ExprProgram(ps, e) -> make_sexp ps "expr_program" [expr_to_sexp e]
| StmtProgram(ps,s,p) -> make_sexp ps "stmt_program" [stmt_to_sexp s; program_to_sexp p]

and stmt_to_sexp (s : stmt_t) : sexp_t = match s with
| ConstStmt(ps,i,e) -> make_sexp ps "const_stmt" [IdentAtom(ps,i);expr_to_sexp e]
| LetStmt(ps,i,e) -> make_sexp ps "let_stmt" [IdentAtom(ps,i);expr_to_sexp e]
| AssignStmt(ps,e1,e2) -> make_sexp ps "assign_stmt" [expr_to_sexp e1;expr_to_sexp e2]

and block_to_sexp (b : block_t) : sexp_t = match b with
| ReturnBlock(ps, e) -> make_sexp ps "return_block" [expr_to_sexp e]
| StmtBlock(ps,s,b) -> make_sexp ps "stmt_block" [stmt_to_sexp s; block_to_sexp b]

and expr_to_sexp (e : expr_t) : sexp_t = match e with
| VarExpr(ps,i) -> make_sexp ps "var_expr" [IdentAtom(ps,i)]
| ValExpr(ps,v) -> make_sexp ps "val_expr" [value_to_sexp v]
| BlockExpr(ps,b) -> make_sexp ps "block_expr" [block_to_sexp b]
| FuncExpr(ps,f) -> make_sexp ps "func_expr" [lambda_to_sexp ps f]
| UopExpr(ps,uop,e) -> make_sexp ps "uop_expr" [uop_to_sexp uop;expr_to_sexp e]
| BopExpr(ps,e1,bop,e2) -> make_sexp ps "bop_expr" [expr_to_sexp e1;bop_to_sexp bop;expr_to_sexp e2]
| CallExpr(ps,e1,el) -> make_sexp ps "call_expr" ([expr_to_sexp e1]@(List.map expr_to_sexp el))
| IfExpr(ps,e1,e2,e3) -> make_sexp ps "if_expr" [expr_to_sexp e1;expr_to_sexp e2;expr_to_sexp e3]
| PrintExpr(ps,e) -> make_sexp ps "print_expr" [expr_to_sexp e]
| FieldExpr(ps,e,f) -> make_sexp ps "field_expr" [expr_to_sexp e;IdentAtom(ps,f)]
| ObjectExpr(ps,fl) -> make_sexp ps "object_expr" (List.map (fun (k,e) -> List(ps,[IdentAtom(ps,k);expr_to_sexp e])) fl)

and lambda_to_sexp ps (name, tl, b, ty) : sexp_t =
  List(ps, [
    List(ps,match name with Some(i) -> [IdentAtom(ps,i)] | _ -> []);
    List(ps,List.map (fun (i,_) -> IdentAtom(ps,i)) tl);
    block_to_sexp b
  ])

and value_to_sexp (v : value_t) : sexp_t =
  value_to_sexp_helper NoPos v true

and value_to_sexp_helper (p : pos_t) (v : value_t) (wrap : bool) : sexp_t =
let make name x = if wrap then make_sexp p name [x] else x in
match v with
| NumVal(n) -> make "num_val" (NumAtom(p, n))
| BoolVal(b) -> make "bool_val" (BoolAtom(p, b))
| StrVal(s) -> make "str_val" (StrAtom(p, s))
| UndefVal -> IdentAtom(NoPos,"undef_val")
| ClosureVal(_,l) -> make "closure_val" (lambda_to_sexp p l)
| RefVal(addr) -> make "ref_val" (NumAtom(p, float_of_int addr))

and uop_to_sexp (b : uop_t) : sexp_t = match b with
| NegUop -> IdentAtom(NoPos,"neg")
| NotUop -> IdentAtom(NoPos,"not")

and bop_to_sexp (b : bop_t) : sexp_t = match b with
| AndBop -> IdentAtom(NoPos,"and")
| OrBop -> IdentAtom(NoPos,"or")
| PlusBop -> IdentAtom(NoPos,"plus")
| MinusBop -> IdentAtom(NoPos,"minus")
| TimesBop -> IdentAtom(NoPos,"times")
| DivBop -> IdentAtom(NoPos,"div")
| EqBop -> IdentAtom(NoPos,"eq")
| NeqBop -> IdentAtom(NoPos,"neq")
| LtBop -> IdentAtom(NoPos,"lt")
| LteBop -> IdentAtom(NoPos,"lte")
| GtBop -> IdentAtom(NoPos,"gt")
| GteBop -> IdentAtom(NoPos,"gte")

let rec result_to_sexp (f : 'a -> sexp_t) (r : ('a,exn) result) : sexp_t =
match r with
| Ok(x) -> f x
| Error(ex) -> exn_to_sexp ex

and exn_to_sexp (ex : exn) : sexp_t = match ex with
| NotExpr(p) -> List(NoPos,[IdentAtom(NoPos,"not_expr");program_to_sexp p])
| ImmutableVar(i) -> List(NoPos,[IdentAtom(NoPos,"immutable_var"); IdentAtom(NoPos,i)])
| UndeclaredVar(i) -> List(NoPos,[IdentAtom(NoPos,"undeclared_var"); IdentAtom(NoPos,i)])
| InvalidCall(e) -> List(NoPos,[IdentAtom(NoPos,"invalid_call"); expr_to_sexp e])
| UnimplementedExpr(e) -> List(NoPos,[IdentAtom(NoPos,"unimplemented_expr"); expr_to_sexp e])
| UnimplementedStmt(s) -> List(NoPos,[IdentAtom(NoPos,"unimplemented_stmt"); stmt_to_sexp s])
| RefError(e) -> List(NoPos,[IdentAtom(NoPos,"ref_error"); expr_to_sexp e])
(*| _ -> failwith (Printf.sprintf "exn_to_sexp: unknown exn: %s" (Printexc.to_string ex))*)
| _ -> List(NoPos,[IdentAtom(NoPos,"error");StrAtom(NoPos,Printexc.to_string ex)])

